name: bc
root: /tmp
pre_window: j boostcache &&
            export PATH=$PATH:$PWD/build &&
            . utils/bash_completion

windows:
  - editor:
      layout: fdcb,273x73,0,0{175x73,0,0,221,97x73,176,0,225}
      panes:
        - vim
        - tig:
          - tig
          # send more keys (settings)
          - r
          - I
  - make:
      panes:
        - prod:
          - mkdir -p .cmake && cd .cmake
          - cmake .. -DCMAKE_BUILD_TYPE=release
        - dev:
          - mkdir -p .cmake-debug && cd .cmake-debug
          - cmake .. -DCMAKE_BUILD_TYPE=debug
            -DBOOSTCACHE_BUILD_DIR=$PWD/build
            -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE
  - bin:
  - tests:
      panes:
        - prod:
          - cd .cmake
          - make runbenchmarks
