name: bc
root: /tmp
pre_window: j boostcache &&
            BC_ROOT=$PWD &&
            BC_PATH_BAK=$PATH &&
            CLANG=$(ls -t /usr/bin/clang-?.? | head -1) &&
            CLANG_PP=$(ls -t /usr/bin/clang++-?.? | head -1) &&
            export PATH=$PATH:$PWD/build &&
            SLEEP_TIMEOUT=5 &&
            function mkcd() { [ -n "$1" ] && mkdir -p "$@" && cd "$1"; } &&
            . utils/bash_completion

windows:
  - editor:
      layout: fdcb,273x73,0,0{175x73,0,0,221,97x73,176,0,225}
      panes:
        - vim:
          - sleep $SLEEP_TIMEOUT && tmux send-keys -t bc:editor.0 'C-p' &
          - vim
        - tig:
          - tig
          # send more keys (settings)
          - r
          - I
  - make:
      layout: tiled
      panes:
        - prod:
          - mkcd .cmake
          - cmake .. -DCMAKE_BUILD_TYPE=releaselto -G Ninja
        - dev:
          - mkcd .cmake-debug
          - export PATH=$PWD/build/bin:$BC_PATH_BAK
          - cmake .. -DCMAKE_BUILD_TYPE=debug
            -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE
            -G Ninja
        - clang:
          - mkcd .cmake-clang
          - export PATH=$PWD/build/bin:$BC_PATH_BAK
          - cmake .. -DCMAKE_BUILD_TYPE=debug
            -DCMAKE_CXX_COMPILER=$CLANG_PP
            -DCMAKE_C_COMPILER=$CLANG
            -G Ninja
  - bin:
  - tests:
      panes:
        - prod:
          - cd .cmake
          - make runbenchmarks
