language: cpp

compiler:
    - gcc
    - clang

before_script:
    - sudo add-apt-repository -y "deb http://ppa.launchpad.net/azat/boost-unofficial/ubuntu natty main"
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ natty-security main restricted"
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ natty main restricted"
    - sudo apt-get update
    - sudo apt-get install -t natty --install-suggests libboost1.53-dev

script:
    - mkdir .cmake
    - cd .cmake
    - cmake ..
    - make
    # TODO: add gtest

branches:
    only:
        - master

# TODO: add notifications
