language: cpp

compiler:
    - gcc

before_script:
    # TODO: replace custom ppa by boost1.54, that contain boost-log library
    - sudo add-apt-repository -y ppa:azat/boost-unofficial
    # HACK: Update gcc it to support c++11
    #
    # We can't use clang because libstdc++4.7 contains a broken definition of std::common_type
    # http://llvm.org/bugs/show_bug.cgi?id=12893
    #
    # TODO: wait for travis-ci/travis-core#195
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ quantal main"
    - sudo apt-get update
    - sudo apt-get install g++
    - sudo apt-get install libboost1.53-all-dev
    - sudo apt-get install gawk gnuplot bc
    # Version of some utils
    - bash --version
    - awk --version
    - gawk --version
    - sed --version
    - gnuplot --version
    - bc --version

script:
    - mkdir .cmake
    - cd .cmake
    - cmake -DCMAKE_BUILD_TYPE=Distribution ..
    - make VERBOSE=1
    - make runbenchmarks
   # Build graphs in terminal
    - make buildplots-dumb
   # TODO: add gtest

branches:
    only:
        - master

env:
    global:
     # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "W0nOcM2fYaA2LZgjT23U/QiqWOcFxT3yqPOmyBzFY9WtFbHPBpRnMYPPvSv9f8zkGw53LjHFYAl9lw4evS1UlF17HQDYU/hpfvNXDXt98idLf+utnzo3MMewX6FtnyZLQYBzmAo2zxRhwrRgT9iwF51l99i7EhP/6bSQh5A3O/I="

addons:
    coverity_scan:
      project:
        name: "azat/boostcache"
        description: "Coverity scan of boostcache"
      notification_email: a3at.mail@gmail.com
      build_command_prepend: cmake .
      build_command: make
      branch_pattern: master

# TODO: add notifications

