language: cpp

compiler:
    - gcc

before_script:
    - sudo apt-get install gawk gnuplot bc
    # - gcc {
    #    HACK: Update gcc it to support c++11
    #
    #    We can't use clang because libstdc++4.7 contains a broken definition of std::common_type
    #    http://llvm.org/bugs/show_bug.cgi?id=12893
    #
    #    TODO: wait for travis-ci/travis-core#195
    # }
    # - cmake: 2.8.12 (>2.8.10)
    # - libboost1.54
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update
    - sudo apt-get install libboost1.54-all-dev libv8-dev
    - sudo apt-get install g++ cmake llvm-3.4 clang-3.4
    # Version of some utils
    - bash --version
    - awk --version
    - gawk --version
    - sed --version
    - gnuplot --version
    - bc --version
    - cmake --version

script:
    - cmake -DCMAKE_BUILD_TYPE=Distribution .
    - make VERBOSE=1
    - make runtests
    - make runsanitizers
    - make runbenchmarks
   # Build graphs in terminal
    - make buildplots-dumb
   # TODO: add gtest

branches:
    only:
        - master

env:
    global:
     # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "W0nOcM2fYaA2LZgjT23U/QiqWOcFxT3yqPOmyBzFY9WtFbHPBpRnMYPPvSv9f8zkGw53LjHFYAl9lw4evS1UlF17HQDYU/hpfvNXDXt98idLf+utnzo3MMewX6FtnyZLQYBzmAo2zxRhwrRgT9iwF51l99i7EhP/6bSQh5A3O/I="

# TODO: add notifications

