language: cpp

compiler:
    # Waiting for next issues:
    #   travis-ci/travis-cookbooks#114
    #   travis-ci/travis-core#195
    # - gcc
    - clang

before_script:
    - sudo add-apt-repository -y ppa:azat/boost-unofficial
    - sudo apt-get update
    - sudo apt-get install libboost1.53-all-dev
    - sudo apt-get install gawk

script:
    - mkdir .cmake
    - cd .cmake
    - cmake ..
    - make
    # Run one_connection
    - ./boostcache -f
    - ../benchmarks/one_connection.sh
    # TODO: add gtest

branches:
    only:
        - master

# TODO: add notifications
