language: cpp

compiler:
    - gcc
    - clang

script:
    - git submodule update --init
    - mkdir .cmake
    - cd .cmake
    - cmake ..
    - make
    # TODO: add gtest

branches:
    only:
        - master

# TODO: add notifications
