language: cpp

compiler:
    - gcc
    - clang

before_script:
    - sudo add-apt-repository -y ppa:azat/boost-unofficial
    - sudo apt-get update
    - sudo apt-get install aptitude
    - sudo aptitude install libboost1.53-all-dev

script:
    - mkdir .cmake
    - cd .cmake
    - cmake ..
    - make
    # TODO: add gtest

branches:
    only:
        - master

# TODO: add notifications
